kafka_version: 0.8.2.1

kafka_dir: /opt/kafka_2.10-{{ kafka_version }}
kafka_tarball_url: http://mirrors.ukfast.co.uk/sites/ftp.apache.org/kafka/{{ kafka_version }}/kafka_2.10-{{ kafka_version }}.tgz

kafka_user: kafka
# handled by systemd
kafka_maxfiles: 64000

kafka_propfile: "{{ kafka_dir }}/config/server.properties"

kafka_zk_url: "{{ groups[zk_group] | join(':2181,') }}:2181/kafka"

# default partitions per topic
kafka_partitions: 10

# log stuff
kafka_log_dir: /var/kafka
kafka_log_dirs:
  - /var/kafka/log1
  - /var/kafka/log2
  - /var/kafka/log3
kafka_retention_hours: 72
# in seconds
kafka_retention_interval: 60
